### ISSUE TITLE
Request not described by WSDL

### ISSUE THREAD

**Issue by jkabat** [php-soap/ext-soap-engine#14]
|    Q        |   A
|------------ | -----
| Version     | 1.3.0

### Support Question

I'm implementing communication with external SOAP which requires secure conversation
(http://schemas.xmlsoap.org/ws/2005/02/sc). This involves requesting a security token, then signing of XML document for each method provided by WSDL service.

My question is how would anyone use library's SOAP client to make a request which is not described by WSDL? It is not supported out of the box, so any tip is welcome.

Action/method which is called for requesting security token is this:
http://schemas.xmlsoap.org/ws/2005/02/trust/RST/SCT

**Comment by veewee** [comment]
Hello @jkabat 

You can use this plugin to do web security stuff:
https://github.com/php-soap/psr18-wsse-middleware

However: if there is a specific method you want to call and this one does not exist in the WSDL - then you'll get errors calling that method, since PHP simply does not knows about that method.

**Comment by jkabat** [comment]
@veewee thank you for fast response.

Yes, Im using this plugin to do the security. But my working version is quite a hack to avoid exception when I try to call method not described in WSDL. I was just curious if there is some better way to do that kind of things.

**Comment by veewee** [comment]
Feel free to share more details about your implementation. Currently it's not clear to me what problem you are facing
