### ISSUE TITLE
How to force CDATA for a specific SOAP Element?

### ISSUE THREAD

**Issue by michabbb** [php-soap/ext-soap-engine#19]
|    Q        |   A
|------------ | -----
| Version     | v1.3.0

hi @veewee,

i hope this project is still alive ;)
eBay had another great idea to make developers crazy 😕 and I have no idea how to solve this with your project, so I please need some help/advise.

based on ebay WSDL I am able to generate the classmap and create a request like this:

```xml
<SOAP-ENV:Body>
        <ns1:ReviseFixedPriceItemRequest>
            <ns1:Item>
                <ns1:Description>&lt;!DOCTYPE html&gt; &lt;!--suppress HtmlFormInputWithoutLabel
                    --&gt; &lt;html&gt; &lt;head&gt; &lt;meta charset="UTF-8"/&gt;
                    &lt;title&gt;Kunde&lt;/title&gt; &lt;meta name="viewport"
                    content="width=device-width,initial-scale=1"/&gt; &lt;link rel="stylesheet"...................
                </ns1:Description>             
               </ns1:Item>
        </ns1:ReviseFixedPriceItemRequest>
    </SOAP-ENV:Body>
````

but ebay forces us (next month) to send this request like that:

```xml
<SOAP-ENV:Body>
    <ns1:ReviseFixedPriceItemRequest>
        <ns1:Item>
            <ns1:Description>
                <![CDATA[
                    <!DOCTYPE html> <!--suppress HtmlFormInputWithoutLabel --> <html> <head> <meta charset="UTF-8"/>
                    <title>Kunde</title> <meta name="viewport" content="width=device-width,initial-scale=1"/> <link rel="stylesheet"...................
                ]]>
            </ns1:Description>            
        </ns1:Item>
    </ns1:ReviseFixedPriceItemRequest>
</SOAP-ENV:Body>
```

and sadly I have absolutely no clue how to make this work.
i would be very happy, if you could help me here !! 🙏 🙏 

[here's the latest trading WSDL of ebay](https://developer.ebay.com/webservices/latest/ebaysvc.wsdl).

thanks !!! 
micha

**Comment by veewee** [comment]
Hello,

The easiest way forward is to add a Type converter:
https://github.com/php-soap/ext-soap-engine#typeconverter

The problem here, is that the `Description` element is a regular `xsd:string` element. It would have been nicer if it were a separate XSD type that could be overwritten.

You can fiddle around with this version a bit in your codebase to see how it behaves.
I tested it from my side and should work OK on basic data - assuming all other HTML fields expect CDATA as well.

```php
<?php

use Soap\ExtSoapEngine\Configuration\TypeConverter\TypeConverterInterface;
use VeeWee\Xml\Dom\Document;

class CDataHtmlStringConverter implements TypeConverterInterface {
    public function getTypeNamespace(): string
    {
        return 'http://www.w3.org/2001/XMLSchema';
    }

    public function getTypeName(): string
    {
        return 'string';
    }

    public function convertXmlToPhp(string $xml)
    {
        $doc = Document::fromXmlString($xml);

        return $doc->toUnsafeDocument()->textContent;
    }

    public function convertPhpToXml($value): string
    {
        if (\strip_tags((string) $value) !== $value) {
            return '<value><![CDATA['.$value.']]></value>';
        }

        return '<value>'.htmlentities($value).'</value>';
    }
}
```

This converter will:

* Check if the string contains HTML tags, if so - it will use CDATA.
* If not, it will use regular string encoding (with htmlentities)

The strings that are coming in, are currently just being passed as-is.
So if you get HTML back wrapped in CDATA, it will contain the data without any html entities.

Since you will be overwriting base xsd strings with this converter - it is a quite impacting change. 
Make sure to test it inside your application broadly :)


--- 

An alternative approach, could be the usage of [SoapVar](https://www.php.net/manual/en/class.soapvar.php) instead of a plain string:

```php
'Description'  => new \SoapVar('<ns1:Description><![CDATA[<html><head><title>hello world</title></head></html>]]></ns1:Description>', XSD_ANYXML),
```

Do note that you need to pass the whole XML tag with a hardcoded namespace. Currently the WSDL only contains one namespace, so that is not a big issue. But if it changes at some point, it might break this logic.

**Comment by michabbb** [comment]
dear toon, thanks a lot for your quick reply !! 
i agree, that the "TypeConverter" is dangerous in some way.
is there a way to use a "TypeConverter" only for specific XML elements ???

**Comment by veewee** [comment]
No, the type-converter has no knowledge of the context it operates on.
It only operates on type:
https://www.php.net/manual/en/soapclient.construct.php#soapclient.construct.options.typemap

As long as your inputs don't (accidentally) contain any HTML tags, it should work just fine with the type converter. It could as well be that the WS accepts CDATA everywhere, making it a non-issue. However, I agree that it would be nicer if they created a custom xsd type for this explicitally in their WSDL.

Since it is something internally in ext-soap, there is nothing we can do about it from this package - until we build our own encoding/decoding system from scratch.

**Comment by michabbb** [comment]
what do you think about this idea: 

i could implement a comment in my HTML that is only used in "Description", something like:

```html
<!-- USE-CDATA-HERE -->
```

and instead of 

```php
if (\strip_tags((string) $value) !== $value) {
```

I could search for exactly that (USE-CDATA-HERE) string 🤔

**Comment by veewee** [comment]
That's also an option.
You could even add the `<![CDATA[    ]]>` part and check to conditionally run htmlentities based on that as well.

At least now you have an idea on how to tackle the issue :)

**Comment by michabbb** [comment]
that sounds even better, I will run some tests on that 😊

**Comment by michabbb** [comment]
@veewee may i ask: 

does [this code](https://github.com/php-soap/ext-soap-engine#typeconverter) (the typeconverter) has to be placed in the "config" or somewhere else, too ??

**Comment by veewee** [comment]
The typemap must be configured on the `ExtSoapOptions` in the generated factory:
https://github.com/phpro/soap-client/blob/master/docs/cli/generate-clientfactory.md

The `config.php` in `phpro/soap-client` is rather to tell code generation how to load the WSDL metadata. 
(That logic will be simplified in [v3](https://github.com/phpro/soap-client/releases/tag/3.0.0-alpha1) a bit by using a separate factory for code generation that doesnt take any ext-soap options anymore.)

**Comment by michabbb** [comment]
okay, got it. will try, thanks !!

**Comment by michabbb** [comment]
@veewee pardon, i have to ask. using "htmlentities" in the "convertPhpToXml" function gives me empty tags when using a string like `Test 123 45°`  - I guess because of the `°`. so I have to ask: did you maybe mean `htmlspecialchars` instead of `htmlentities` 🤔

**Comment by veewee** [comment]
`htmlentities` can take the `ENT_QUOTES` flag. I've used that function because it handles other special characters besides the regular html once as well. But you can play around with that and see what works for you.

(you could also use [DOMDocument to build valid xml](https://github.com/veewee/xml/blob/main/docs/dom.md#builders) - but it seems I haven't got any builder for cdata yet.)

I am a bit confused on why a quote will result in an empty tag though: 

```xml
<hello>world"</hello>
```
This is perfectly valid - unless it gets injected in an attribute.

**Comment by michabbb** [comment]
The problem seems to be the the "degree" sign (in my example) , I am confused as well. So I switched to "htmlspecialchars" and that worked, because the ° sign doesn't need to be encoded...

I can create a demo repository in case you like to check that.....?

**Comment by michabbb** [comment]
i guess i will stick with the 2nd solution, because it´s too dangerous in my eyes to touch "everything", when there is only one specific tag, that needs to be changed.

@veewee is there any method available to change a specific variable inside a specific class while classes get generated ?
so that this:

```php
public function setDescription(string $Description)
    {
         $this->Description = $Description;
         return $this;
    }
```
becomes this:
```php
public function setDescription(string $Description)
    {
        if (!empty($Description)) {
            $this->Description  = new SoapVar('<ns1:Description><![CDATA['.$Description.']]></ns1:Description>', XSD_ANYXML);
        }
        return $this;
    }
```

❓ ❓

**Comment by veewee** [comment]
That sure is possible by creating your own [custom assembler](https://github.com/phpro/soap-client/blob/master/docs/code-generation/assemblers.md#creating-your-own-assembler)  that contains the code-geberation for this specific type of setter. You might want to place it after the regular `FluentSetterAssembler` and remove the set method if it already exist.

As a base, you could start by copying this class and alter it to your needs:
https://github.com/phpro/soap-client/blob/master/src/Phpro/SoapClient/CodeGenerator/Assembler/FluentSetterAssembler.php

You might also need to create a [code generation rule](https://github.com/phpro/soap-client/blob/master/docs/code-generation/rules.md) that matches on **both** a TYPE name and a PROPERTY name. Unless you want to apply it on any "Description" property.

**Comment by michabbb** [comment]
That´s exactly what makes this framework so powerful ❤️ 😊

**Comment by veewee** [comment]
Hello there @michabbb ,

I wanted to get back to this issue:
We are finishing up v4 of the soap-client package which uses a new encoding system internally.
With this new system, you should be able to get around this issue more easily.

We are eager to receive some early feedback on this new release.
If you got some time, feel free to play around with the alpha version:


* Release: https://github.com/phpro/soap-client/releases/tag/4.0.0-alpha1
* Discussion: https://github.com/phpro/soap-client/discussions/527

**Comment by michabbb** [comment]
@veewee thanks a lot for letting me know. i am currently not in this, but as soon as I have to deal with this again, I am more than happy, to test this! thanks !
